### ISSUE TITLE
ServerMessage not parsing correctly

### ISSUE THREAD

**Issue by satu** [robotty/twitch-irc-rs#114]
I guess this type of message is new and not supported yet. It's a message that I saw today shortly after being raided (the raid message itself didn't cause any error):

```
2021-02-27 17:01:34,327 ERROR [twitch_irc::connection::event_loop] Failed to parse incoming message as ServerMessage (emitting as generic instead): Could not parse IRC message :jtv!jtv@jtv.tmi.twitch.tv PRIVMSG stuck_overflow :laempie is now hosting you for up to 6 viewers. as ServerMessage: Malformed channel parameter (# must be present + something after it)
```

**Comment by RAnders00** [comment]
This is puzzling me, I've never seen the Twitch IRC servers emit a message that looked anything like that. I specifically wrote the library to gracefully handle messages like these that are a bit malformed but still conform to the IRC spec.

In this case the library behaved as I intended it to, since the message did not follow the format specified by Twitch (https://dev.twitch.tv/docs/irc/commands#notice-twitch-commands) it did a graceful fallback and just emitted it as `ServerMessage::Generic`.

I will file a bug report with Twitch to confirm that this is a bug on their end. But for now I don't think I need to fix any bug here, I think this is a bug with Twitch emitting messages not conforming to their spec.

**Comment by RAnders00** [comment]
It now occurred to me that it‘s possible to `client.join("channel_a,channel_b")` which causes this bug apparently (see the linked issue). Should the library throw an error (panic? warning in the logging output?) when an invalid channel name is encountered?
